# Generated by Django 5.0.2 on 2024-03-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='price',
            new_name='total_price',
        ),
    ]
