# Generated by Django 5.0.2 on 2024-03-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_price_cartorder_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='product_status',
        ),
    ]
