# Generated by Django 5.0.2 on 2024-03-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cartorderitem_product_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItem',
            new_name='CartOrderDetail',
        ),
        migrations.AlterModelOptions(
            name='cartorderdetail',
            options={'verbose_name_plural': 'Cart Order Details'},
        ),
    ]
